### ISSUE TITLE
libfolia/foliautils.h: No such file or directory

### ISSUE THREAD

**Issue by KDercksen** [proycon/python-frog#2]
I'm trying to install `python-frog` on Debian Jessie manually, getting this error. I'm not sure if it's a dependency problem on my side or a mistake in the code somewhere.

Output:

> (thesis)koen@baas:~/projects/thesis/python-frog$ python setup.py install
> /usr/lib/python3.4/distutils/extension.py:132: UserWarning: Unknown Extension options: 'pyrex_gdb'
>   warnings.warn(msg)
> running install
> running build
> running build_ext
> skipping 'frog_wrapper.cpp' Cython extension (up-to-date)
> building 'frog' extension
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/home/koen/venvs/thesis/include -I/home/koen/local/include/ -I/usr/include/ -I/usr/include/libxml2 -I/usr/local/include/ -I/usr/include/python3.4m -I/home/koen/venvs/thesis/include/python3.4m -c frog_wrapper.cpp -o build/temp.linux-x86_64-3.4/frog_wrapper.o --std=c++0x
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> frog_wrapper.cpp:257:33: fatal error: libfolia/foliautils.h: No such file or directory
>  #include "libfolia/foliautils.h"
>                                  ^
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by KDercksen** [comment]
So it was a dependency issue, nevermind this..

**Comment by proycon** [comment]
Glad you resolved it already :) It was a missing `libfolia` indeed.

**Comment by Poezedoez** [comment]
Hi there,
I was wondering if you could help me with an error I got trying to run frog on LaMachine. I am already able to run it manually in the VM command line like this: frog -file. However, since I want to run it on a large dataset, I need to frog one document at a time in a loop. I am trying to run my own frog.py on the VM that contains the example code, but I get the following error: 
![error](https://cloud.githubusercontent.com/assets/8011906/15087123/4c440b96-13e6-11e6-96c6-a22269ef3321.png)
Caused by example code:
![code](https://cloud.githubusercontent.com/assets/8011906/15087155/8e249e0e-13e6-11e6-8c24-6d141e2e4fa1.png)
Looks like the VM is not able to find the module at all, but I have no idea how it could.
Do you have any idea?
